/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "outline-variant": "#c5c6cd",
        "on-secondary-fixed-variant": "#005049",
        "primary-container": "#1e293b",
        "surface-variant": "#e0e3e5",
        "surface-container-high": "#e6e8ea",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#6bd8cb",
        "surface-container": "#eceef0",
        "on-surface": "#191c1e",
        "tertiary-container": "#422000",
        "on-secondary-fixed": "#00201d",
        "surface-bright": "#f7f9fb",
        "error": "#ba1a1a",
        "on-primary-container": "#94a3b8",
        "on-tertiary-fixed-variant": "#6e3900",
        "secondary": "#006a61",
        "on-tertiary-fixed": "#2f1500",
        "primary-fixed-dim": "#bcc7de",
        "tertiary": "#240f00",
        "inverse-on-surface": "#eff1f3",
        "surface-container-highest": "#e0e3e5",
        "surface-tint": "#545f73",
        "inverse-primary": "#bcc7de",
        "outline": "#75777d",
        "inverse-surface": "#2d3133",
        "surface-dim": "#d8dadc",
        "on-background": "#191c1e",
        "on-tertiary-container": "#d97705",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#d8e3fb",
        "secondary-fixed": "#89f5e7",
        "surface": "#f7f9fb",
        "on-error": "#ffffff",
        "on-secondary-container": "#6bd8cb",
        "tertiary-fixed": "#ffdcc3",
        "secondary-container": "#86f2e4",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#111c2d",
        "surface-container-low": "#f2f4f6",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#ffb77d",
        "primary": "#091426",
        "on-surface-variant": "#94a3b8",
        "on-primary-fixed-variant": "#3c475a",
        "background": "#020617",
        "surface-container-lowest": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "1rem",
        "2xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        xl: "64px",
        gutter: "24px",
        sm: "12px",
        "margin-desktop": "48px",
        lg: "40px",
        "margin-mobile": "16px",
        md: "24px",
        xs: "4px",
        base: "8px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "title-md": ["22px", { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "body-lg": ["19px", { lineHeight: "30px", fontWeight: "400" }],
        "caption": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
      keyframes: {
        "float": {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-20px)" },
        },
        "float-subtle": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "slide-up": {
          from: { opacity: "0", transform: "translateY(32px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "progress-bar": {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(200%)" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.9)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        "spin": {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
        "shimmer": {
          "100%": { transform: "translateX(100%)" },
        },
        "bounce-short": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-15%)" },
        }
      },
      animation: {
        "float": "float 6s ease-in-out infinite",
        "float-subtle": "float-subtle 6s ease-in-out infinite",
        "float-delayed": "float 6s ease-in-out infinite -2s",
        "fade-in": "fade-in 0.6s ease-out forwards",
        "slide-up": "slide-up 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "progress-bar": "progress-bar 1.5s ease-in-out infinite",
        "scale-in": "scale-in 0.4s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "spin": "spin 1s linear infinite",
        "shimmer": "shimmer 1.5s infinite",
        "bounce-short": "bounce-short 0.5s ease-in-out 1",
      },
    },
  },
  plugins: [],
};
